apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pakalspot-application-set
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            namespace: pakalspot-dev
            branch: dev
            autoSync: "true"
          - name: staging
            namespace: pakalspot-staging
            branch: staging
            autoSync: "false"
          - name: prod
            namespace: pakalspot-prod
            branch: main
            autoSync: "false"
          - name: k8sfinal
            namespace: pakalspot-k8sfinal
            branch: k8sfinal
            autoSync: "true"
  template:
    metadata:
      name: "pakalspot-{{name}}"
      namespace: argocd
    spec:
      project: default
      sources:
        - repoURL: https://github.com/yaakovsm/pakalspot-gitops
          targetRevision: main
          ref: gitops 
        - repoURL: https://github.com/yaakovsm/pakalspot-application
          targetRevision: "{{branch}}"
          path: pakalspot-chart
          helm:
            valueFiles:
              - $gitops/common-settings.yaml
              - $gitops/environments/{{name}}/values.yaml    
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true