app:
  environment: dev
  namespace: pakalspot-dev
global:
  image:
    tag: ''
frontend:
  replicaCount: 1
  image:
    tag: dev-d066847
    pullPolicy: Always
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    VITE_ALLOWED_HOSTS: all
backend:
  replicaCount: 1
  image:
    tag: dev-d066847
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8000
    nlbAnnotations: null
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  podAnnotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8000'
    prometheus.io/path: /metrics
  env:
    DEBUG: 'true'
    ENVIRONMENT: development
    S3_BUCKET: pakalspot-photos
    BASE_URL: http://pakalspot.local
database:
  enabled: false
secrets:
  database:
    POSTGRES_PASSWORD: dev_password_secure
ingress:
  enabled: true
autoscaling:
  enabled: false
podDisruptionBudget:
  enabled: false
networkPolicy:
  enabled: false
monitoring:
  enabled: false
serviceAccount:
  create: true
  automount: true
  irsaRoleArn: ''
  annotations: {}
